abstract: Build URI by action name, namespace, and args
author: Toru Yamaguchi <zigorou@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-BuildURI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
  URI: 0
version: 0.0.1
